# Generated by Django 4.1.3 on 2023-04-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie_Handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cookie', models.CharField(max_length=100)),
                ('User', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('User', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
                ('Level', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
                ('Rate', models.CharField(max_length=100, null=True)),
                ('Interest', models.CharField(max_length=100, null=True)),
                ('Sales', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=100)),
                ('Student', models.IntegerField()),
                ('Level', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100, null=True)),
                ('Last_Seen', models.CharField(max_length=100, null=True)),
                ('Days_Left', models.CharField(max_length=100, null=True)),
                ('Verify', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=100)),
                ('Student', models.IntegerField()),
                ('Question', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100, null=True)),
                ('School_Name', models.CharField(max_length=100, null=True)),
                ('School_Type', models.CharField(max_length=100, null=True)),
                ('School_Descriptions', models.CharField(max_length=2000, null=True)),
                ('Plans', models.CharField(max_length=100, null=True)),
                ('Currency', models.CharField(max_length=100, null=True)),
                ('Last_Seen', models.CharField(max_length=100, null=True)),
                ('Days_Left', models.CharField(max_length=100, null=True)),
                ('Verify', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.IntegerField()),
                ('Topic', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('User', models.IntegerField()),
                ('Course', models.IntegerField()),
                ('Level', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=100)),
                ('User', models.IntegerField()),
                ('Link', models.CharField(max_length=1000)),
                ('Description', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=100)),
                ('User', models.IntegerField()),
                ('Question', models.CharField(max_length=1000)),
                ('A_answer', models.CharField(max_length=1000)),
                ('B_answer', models.CharField(max_length=1000)),
                ('C_answer', models.CharField(max_length=1000)),
                ('D_answer', models.CharField(max_length=1000)),
                ('Answer', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=100)),
                ('User', models.IntegerField()),
                ('Link', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
