# Generated by Django 4.1.3 on 2023-04-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_courses',
            name='User',
            field=models.CharField(default='r', max_length=344),
            preserve_default=False,
        ),
    ]
