# Generated by Django 4.1.3 on 2023-04-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0002_student_courses_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_courses',
            name='User',
            field=models.IntegerField(),
        ),
    ]
