# Generated by Django 4.1.3 on 2023-04-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0003_alter_student_courses_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.IntegerField(max_length=100)),
                ('Info', models.CharField(max_length=1000)),
                ('Type', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
