# Generated by Django 4.1.3 on 2023-04-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0004_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_courses',
            name='User',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='Uid',
            field=models.IntegerField(),
        ),
    ]
