# Generated by Django 4.1.3 on 2023-04-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0005_remove_student_courses_user_alter_notifications_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_courses',
            name='User',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
