# Generated by Django 4.1.3 on 2023-04-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0006_student_courses_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField()),
                ('Uid', models.CharField(max_length=1000)),
                ('Type', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
