# Generated by Django 4.1.3 on 2023-04-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0007_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_info',
            name='Description',
            field=models.CharField(default="Our brands BMW, MINI, Rolls-Royce and BMW Motorrad have made us one of the world's leading premium manufacturer of cars and", max_length=5000),
            preserve_default=False,
        ),
    ]
