# Generated by Django 4.1.3 on 2023-04-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0009_admin_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_courses',
            name='Type',
            field=models.CharField(default='Paid', max_length=100),
            preserve_default=False,
        ),
    ]
