# Generated by Django 4.1.3 on 2023-04-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0011_module_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_info',
            name='Module',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
